<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="879347" started-at="2015-10-21T21:26:56Z" finished-at="2015-10-21T21:41:35Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="879347" started-at="2015-10-21T21:26:56Z" finished-at="2015-10-21T21:41:35Z">
      <class name="com.tools.framework.tests.SignUpValidUsingFramework">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:com.tools.framework.tests.SignUpValidUsingFramework@4c40b76e]" name="beforeMethod" is-config="true" duration-ms="5987" started-at="2015-10-21T14:26:56Z" finished-at="2015-10-21T14:27:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="run()[pri:0, instance:com.tools.framework.tests.SignUpValidUsingFramework@4c40b76e]" name="run" duration-ms="873137" started-at="2015-10-21T14:27:02Z" finished-at="2015-10-21T14:41:35Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.tools.framework.tests.SignUpValidUsingFramework.run(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- run -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:com.tools.framework.tests.SignUpValidUsingFramework@4c40b76e]" name="afterMethod" is-config="true" duration-ms="211" started-at="2015-10-21T14:41:35Z" finished-at="2015-10-21T14:41:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- com.tools.framework.tests.SignUpValidUsingFramework -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
